{
	"title": "CVE-2014-0472",
	"cve": "CVE-2014-0472",
	"notes": [
		{
			"type": "Description",
			"text": "The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\""
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2014-04-23"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2017-01-04"
		}
	],
	"references": [
		{
			"url": "https://www.djangoproject.com/weblog/2014/apr/21/security/",
			"description": "CONFIRM:https://www.djangoproject.com/weblog/2014/apr/21/security/"
		},
		{
			"url": "http://www.debian.org/security/2014/dsa-2934",
			"description": "DEBIAN:DSA-2934"
		},
		{
			"url": "http://rhn.redhat.com/errata/RHSA-2014-0456.html",
			"description": "REDHAT:RHSA-2014:0456"
		},
		{
			"url": "http://rhn.redhat.com/errata/RHSA-2014-0457.html",
			"description": "REDHAT:RHSA-2014:0457"
		},
		{
			"url": "http://secunia.com/advisories/61281",
			"description": "SECUNIA:61281"
		},
		{
			"url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html",
			"description": "SUSE:openSUSE-SU-2014:1132"
		},
		{
			"url": "http://www.ubuntu.com/usn/USN-2169-1",
			"description": "UBUNTU:USN-2169-1"
		}
	]
}
