{
	"title": "CVE-2024-0229",
	"cve": "CVE-2024-0229",
	"notes": {
		"description": "An out-of-bounds memory access flaw was found in the X.Org server. This issue can be triggered when a device frozen by a sync grab is reattached to a different master device. This issue may lead to an application crash, local privilege escalation (if the server runs with extended privileges), or remote code execution in SSH X11 forwarding environments.",
		"published": "2024-02-09",
		"modified": "2024-02-09"
	},
	"references": [
		{
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2256690",
			"description": "MISC:RHBZ#2256690"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0320",
			"description": "MISC:RHSA-2024:0320"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0557",
			"description": "MISC:RHSA-2024:0557"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0558",
			"description": "MISC:RHSA-2024:0558"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0597",
			"description": "MISC:RHSA-2024:0597"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0607",
			"description": "MISC:RHSA-2024:0607"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0614",
			"description": "MISC:RHSA-2024:0614"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0617",
			"description": "MISC:RHSA-2024:0617"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0621",
			"description": "MISC:RHSA-2024:0621"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0626",
			"description": "MISC:RHSA-2024:0626"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2024:0629",
			"description": "MISC:RHSA-2024:0629"
		},
		{
			"url": "https://access.redhat.com/security/cve/CVE-2024-0229",
			"description": "MISC:https://access.redhat.com/security/cve/CVE-2024-0229"
		}
	]
}
