{
	"title": "CVE-2017-15126",
	"cve": "CVE-2017-15126",
	"notes": {
		"description": "A use-after-free flaw was found in fs/userfaultfd.c in the Linux kernel before 4.13.6. The issue is related to the handling of fork failure when dealing with event messages. Failure to fork correctly can lead to a situation where a fork event will be removed from an already freed list of events with userfaultfd_ctx_put().",
		"published": "2018-01-14",
		"modified": "2023-02-12"
	},
	"references": [
		{
			"url": "http://www.securityfocus.com/bid/102516",
			"description": "MISC:102516"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:0676",
			"description": "MISC:RHSA-2018:0676"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:1062",
			"description": "MISC:RHSA-2018:1062"
		},
		{
			"url": "http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=384632e67e0829deb8015ee6ad916b180049d252",
			"description": "MISC:http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=384632e67e0829deb8015ee6ad916b180049d252"
		},
		{
			"url": "https://access.redhat.com/security/cve/CVE-2017-15126",
			"description": "MISC:https://access.redhat.com/security/cve/CVE-2017-15126"
		},
		{
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1523481",
			"description": "MISC:https://bugzilla.redhat.com/show_bug.cgi?id=1523481"
		},
		{
			"url": "https://github.com/torvalds/linux/commit/384632e67e0829deb8015ee6ad916b180049d252",
			"description": "MISC:https://github.com/torvalds/linux/commit/384632e67e0829deb8015ee6ad916b180049d252"
		},
		{
			"url": "https://www.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.6",
			"description": "MISC:https://www.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.6"
		}
	]
}
