{
	"title": "CVE-2019-19588",
	"cve": "CVE-2019-19588",
	"notes": [
		{
			"type": "Description",
			"text": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2019-12-04"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2019-12-04"
		}
	],
	"references": [
		{
			"url": "https://github.com/kvesteri/validators/issues/86",
			"description": "MISC:https://github.com/kvesteri/validators/issues/86"
		}
	]
}
