{
	"title": "CVE-2019-14491",
	"cve": "CVE-2019-14491",
	"notes": {
		"description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
		"published": "2019-08-01",
		"modified": "2019-12-11"
	},
	"references": [
		{
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HPFLN6QAX6SUA4XR4NMKKXX26H3TYCVQ/",
			"description": "FEDORA:FEDORA-2019-20ef0e76fe"
		},
		{
			"url": "https://github.com/opencv/opencv/compare/33b765d...4a7ca5a",
			"description": "MISC:https://github.com/opencv/opencv/compare/33b765d...4a7ca5a"
		},
		{
			"url": "https://github.com/opencv/opencv/compare/371bba8...ddbd10c",
			"description": "MISC:https://github.com/opencv/opencv/compare/371bba8...ddbd10c"
		},
		{
			"url": "https://github.com/opencv/opencv/issues/15125",
			"description": "MISC:https://github.com/opencv/opencv/issues/15125"
		},
		{
			"url": "http://lists.opensuse.org/opensuse-security-announce/2019-12/msg00025.html",
			"description": "SUSE:openSUSE-SU-2019:2671"
		}
	]
}
