{
	"title": "CVE-2019-16227",
	"cve": "CVE-2019-16227",
	"notes": [
		{
			"type": "Description",
			"text": "An issue was discovered in py-lmdb 0.97. For certain values of mn_flags, mdb_cursor_set triggers a memcpy with an invalid write operation within mdb_xcursor_init1. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2019-09-11"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2019-10-12"
		}
	],
	"references": [
		{
			"url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memcpy%20illegal%20dst",
			"description": "MISC:https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memcpy%20illegal%20dst"
		}
	]
}
