{
  "title": "CVE-2019-1010142",
  "cve": "CVE-2019-1010142",
  "notes": {
    "description": "scapy 2.4.0 is affected by: Denial of Service. The impact is: infinite loop, resource consumption and program unresponsive. The component is: _RADIUSAttrPacketListField.getfield(self..). The attack vector is: over the network or in a pcap. both work.",
    "published": "2019-07-19",
    "modified": "2019-10-20"
  },
  "references": [
    {
      "url": "http://www.securityfocus.com/bid/106674",
      "description": "BID:106674"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T46XW4S5BCA3VV3JT3C5Q6LBEXSIACLN/",
      "description": "FEDORA:FEDORA-2019-47946eb312"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/42NRPMC3NS2QVFNIXYP6WV2T3LMLLY7E/",
      "description": "FEDORA:FEDORA-2019-d49c8ec32b"
    },
    {
      "url": "https://github.com/secdev/scapy/pull/1409",
      "description": "MISC:https://github.com/secdev/scapy/pull/1409"
    },
    {
      "url": "https://github.com/secdev/scapy/pull/1409/files#diff-441eff981e466959968111fc6314fe93L1058",
      "description": "MISC:https://github.com/secdev/scapy/pull/1409/files#diff-441eff981e466959968111fc6314fe93L1058"
    },
    {
      "url": "https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/",
      "description": "MISC:https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/"
    }
  ]
}
