{
	"title": "CVE-2010-1634",
	"cve": "CVE-2010-1634",
	"notes": [
		{
			"type": "Description",
			"text": "Multiple integer overflows in audioop.c in the audioop module in Python 2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial of service (application crash) via a large fragment, as demonstrated by a call to audioop.lin2lin with a long string in the first argument, leading to a buffer overflow. NOTE: this vulnerability exists because of an incorrect fix for CVE-2008-3143.5."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2010-05-27"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2023-02-12"
		}
	],
	"references": [
		{
			"url": "http://secunia.com/advisories/39937",
			"description": "MISC:39937"
		},
		{
			"url": "http://secunia.com/advisories/40194",
			"description": "MISC:40194"
		},
		{
			"url": "http://www.securityfocus.com/bid/40370",
			"description": "MISC:40370"
		},
		{
			"url": "http://secunia.com/advisories/42888",
			"description": "MISC:42888"
		},
		{
			"url": "http://secunia.com/advisories/43068",
			"description": "MISC:43068"
		},
		{
			"url": "http://secunia.com/advisories/50858",
			"description": "MISC:50858"
		},
		{
			"url": "http://secunia.com/advisories/51024",
			"description": "MISC:51024"
		},
		{
			"url": "http://secunia.com/advisories/51040",
			"description": "MISC:51040"
		},
		{
			"url": "http://secunia.com/advisories/51087",
			"description": "MISC:51087"
		},
		{
			"url": "http://www.vupen.com/english/advisories/2010/1448",
			"description": "MISC:ADV-2010-1448"
		},
		{
			"url": "http://www.vupen.com/english/advisories/2011/0122",
			"description": "MISC:ADV-2011-0122"
		},
		{
			"url": "http://www.vupen.com/english/advisories/2011/0212",
			"description": "MISC:ADV-2011-0212"
		},
		{
			"url": "http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html",
			"description": "MISC:APPLE-SA-2011-10-12-3"
		},
		{
			"url": "http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html",
			"description": "MISC:FEDORA-2010-9652"
		},
		{
			"url": "http://www.redhat.com/support/errata/RHSA-2011-0027.html",
			"description": "MISC:RHSA-2011:0027"
		},
		{
			"url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html",
			"description": "MISC:SUSE-SR:2010:024"
		},
		{
			"url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html",
			"description": "MISC:SUSE-SR:2011:002"
		},
		{
			"url": "http://www.ubuntu.com/usn/USN-1596-1",
			"description": "MISC:USN-1596-1"
		},
		{
			"url": "http://www.ubuntu.com/usn/USN-1613-1",
			"description": "MISC:USN-1613-1"
		},
		{
			"url": "http://www.ubuntu.com/usn/USN-1613-2",
			"description": "MISC:USN-1613-2"
		},
		{
			"url": "http://www.ubuntu.com/usn/USN-1616-1",
			"description": "MISC:USN-1616-1"
		},
		{
			"url": "http://bugs.python.org/issue8674",
			"description": "MISC:http://bugs.python.org/issue8674"
		},
		{
			"url": "http://support.apple.com/kb/HT5002",
			"description": "MISC:http://support.apple.com/kb/HT5002"
		},
		{
			"url": "http://svn.python.org/view?rev=81045&view=rev",
			"description": "MISC:http://svn.python.org/view?rev=81045&view=rev"
		},
		{
			"url": "http://svn.python.org/view?rev=81079&view=rev",
			"description": "MISC:http://svn.python.org/view?rev=81079&view=rev"
		},
		{
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690",
			"description": "MISC:https://bugzilla.redhat.com/show_bug.cgi?id=590690"
		}
	]
}
