{
	"title": "CVE-2020-5274",
	"cve": "CVE-2020-5274",
	"notes": {
		"description": "In Symfony before versions 5.0.5 and 4.4.5, some properties of the Exception were not properly escaped when the `ErrorHandler` rendered it stacktrace. In addition, the stacktrace were displayed even in a non-debug configuration. The ErrorHandler now escape alls properties of the exception, and the stacktrace is only display in debug configuration. This issue is patched in symfony/http-foundation versions 4.4.5 and 5.0.5",
		"published": "2020-03-30",
		"modified": "2020-03-30"
	},
	"references": [
		{
			"url": "https://github.com/symfony/symfony/security/advisories/GHSA-m884-279h-32v2",
			"description": "CONFIRM:https://github.com/symfony/symfony/security/advisories/GHSA-m884-279h-32v2"
		},
		{
			"url": "https://github.com/symfony/symfony/commit/629d21b800a15dc649fb0ae9ed7cd9211e7e45db",
			"description": "MISC:https://github.com/symfony/symfony/commit/629d21b800a15dc649fb0ae9ed7cd9211e7e45db"
		},
		{
			"url": "https://github.com/symfony/symfony/commit/cf80224589ac05402d4f72f5ddf80900ec94d5ad",
			"description": "MISC:https://github.com/symfony/symfony/commit/cf80224589ac05402d4f72f5ddf80900ec94d5ad"
		}
	]
}
