{
  "title": "CVE-2020-8492",
  "cve": "CVE-2020-8492",
  "notes": {
    "description": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.",
    "published": "2020-01-30",
    "modified": "2023-05-24"
  },
  "references": [
    {
      "url": "https://security.netapp.com/advisory/ntap-20200221-0001/",
      "description": "CONFIRM:https://security.netapp.com/advisory/ntap-20200221-0001/"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WOKDEXLYW5UQ4S7PA7E37IITOC7C56J/",
      "description": "FEDORA:FEDORA-2020-6a88dad4a0"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/",
      "description": "FEDORA:FEDORA-2020-8bdd3fd7a4"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APGWEMYZIY5VHLCSZ3HD67PA5Z2UQFGH/",
      "description": "FEDORA:FEDORA-2020-98e0f0f11b"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/",
      "description": "FEDORA:FEDORA-2020-ea5bdbcc90"
    },
    {
      "url": "https://security.gentoo.org/glsa/202005-09",
      "description": "GENTOO:GLSA-202005-09"
    },
    {
      "url": "https://bugs.python.org/issue39503",
      "description": "MISC:https://bugs.python.org/issue39503"
    },
    {
      "url": "https://github.com/python/cpython/pull/18284",
      "description": "MISC:https://github.com/python/cpython/pull/18284"
    },
    {
      "url": "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html",
      "description": "MISC:https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html"
    },
    {
      "url": "https://lists.apache.org/thread.html/rdb31a608dd6758c6093fd645aea3fbf022dd25b37109b6aaea5bc0b5@%3Ccommits.cassandra.apache.org%3E",
      "description": "MLIST:[cassandra-commits] 20210816 [jira] [Created] (CASSANDRA-16857) Security vulnerability CVE-2020-8492"
    },
    {
      "url": "https://lists.apache.org/thread.html/rfec113c733162b39633fd86a2d0f34bf42ac35f711b3ec1835c774da@%3Ccommits.cassandra.apache.org%3E",
      "description": "MLIST:[cassandra-commits] 20210816 [jira] [Updated] (CASSANDRA-16857) Security vulnerability CVE-2020-8492"
    },
    {
      "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html",
      "description": "MLIST:[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update"
    },
    {
      "url": "https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html",
      "description": "MLIST:[debian-lts-announce] 20230524 [SECURITY] [DLA 3432-1] python2.7 security update"
    },
    {
      "url": "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html",
      "description": "SUSE:openSUSE-SU-2020:0274"
    },
    {
      "url": "https://usn.ubuntu.com/4333-1/",
      "description": "UBUNTU:USN-4333-1"
    },
    {
      "url": "https://usn.ubuntu.com/4333-2/",
      "description": "UBUNTU:USN-4333-2"
    }
  ]
}
