{
	"title": "CVE-2021-20213",
	"cve": "CVE-2021-20213",
	"notes": [
		{
			"type": "Description",
			"text": "A flaw was found in Privoxy in versions before 3.0.29. Dereference of a NULL-pointer that could result in a crash if accept-intercepted-requests was enabled, Privoxy failed to get the request destination from the Host header and a memory allocation failed."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2021-03-25"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2021-07-08"
		}
	],
	"references": [
		{
			"url": "https://security.gentoo.org/glsa/202107-16",
			"description": "GENTOO:GLSA-202107-16"
		},
		{
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1928739",
			"description": "MISC:https://bugzilla.redhat.com/show_bug.cgi?id=1928739"
		},
		{
			"url": "https://www.privoxy.org/3.0.29/user-manual/whatsnew.html",
			"description": "MISC:https://www.privoxy.org/3.0.29/user-manual/whatsnew.html"
		}
	]
}
